### ISSUE TITLE
Where do I find the config file?

### ISSUE THREAD

**Issue by unklebonehead** [YunoHost-Apps/prosody_ynh#11]
Im using Yunohost 11.0.9.14 on a beefy old laptop. i5 16gb ram.

I want to make my prosody public and allow account creation. Where do I find the config file(s) in Yunohost?

**Comment by yalh76** [comment]
prosody_ynh was implemented because prosody it's required for jitsi_ynh and live plugin of peertube_ynh. It was not planned to be directly used, so you should look at metronome already included in yunohost, a fork of prosody.

**Comment by asandikci** [comment]
> prosody_ynh was implemented because prosody it's required for jitsi_ynh and live plugin of peertube_ynh. It was not planned to be directly used, so you should look at metronome already included in yunohost, a fork of prosody.

@yalh76 Is situation still same? If yes, isn't it mention this in readme would be good?

**Comment by yalh76** [comment]
> > prosody_ynh was implemented because prosody it's required for jitsi_ynh and live plugin of peertube_ynh. It was not planned to be directly used, so you should look at metronome already included in yunohost, a fork of prosody.
> 
> [@yalh76](https://github.com/yalh76) Is situation still same? If yes, isn't it mention this in readme would be good?

Yes, situation mostly the same.

The only difference is: Metronome is no more directly included in YunoHost. But Metronome should have a better integration in YunoHost, so it's better to use it.

Feel free to do a PR to add informations in the Readme, 

There is an ongoing PR #28 to improve integration of prosody
