### ISSUE TITLE
Prosody fails after upgrade to 0.12.3~ynh2

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/prosody_ynh#15]
### Describe the bug

It's been reported on Matrix support channel that Prosody fails to start after the latest update. General failure is along the lines of

> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: Prosody was unable to find luaexpat
> août 06 15:01:06 prosody[764741]: This package can be obtained in the following ways:
> août 06 15:01:06 prosody[764741]:   Debian/Ubuntu | sudo apt install lua-expat
> août 06 15:01:06 prosody[764741]:        luarocks | luarocks install luaexpat
> août 06 15:01:06 prosody[764741]:          Source | http://matthewwild.co.uk/projects/luaexpat/
> août 06 15:01:06 prosody[764741]: luaexpat is required for Prosody to run, so we will now exit.
> août 06 15:01:06 prosody[764741]: More help can be found on our website, at https://prosody.im/doc/depends
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: Prosody was unable to find luasocket
> août 06 15:01:06 prosody[764741]: This package can be obtained in the following ways:
> août 06 15:01:06 prosody[764741]:   Debian/Ubuntu | sudo apt install lua-socket
> août 06 15:01:06 prosody[764741]:        luarocks | luarocks install luasocket
> août 06 15:01:06 prosody[764741]:          Source | http://www.tecgraf.puc-rio.br/~diego/professional/luasocket/
> août 06 15:01:06 prosody[764741]: luasocket is required for Prosody to run, so we will now exit.
> août 06 15:01:06 prosody[764741]: More help can be found on our website, at https://prosody.im/doc/depends
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: Prosody was unable to find LuaSec
> août 06 15:01:06 prosody[764741]: This package can be obtained in the following ways:
> août 06 15:01:06 prosody[764741]:   Debian/Ubuntu | sudo apt install lua-sec
> août 06 15:01:06 prosody[764741]:        luarocks | luarocks install luasec
> août 06 15:01:06 prosody[764741]:          Source | https://github.com/brunoos/luasec
> août 06 15:01:06 prosody[764741]: LuaSec is required for Prosody to run, so we will now exit.
> août 06 15:01:06 prosody[764741]: More help can be found on our website, at https://prosody.im/doc/depends
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 prosody[764741]: Prosody was unable to find lua-unbound
> août 06 15:01:06 prosody[764741]: This package can be obtained in the following ways:
> août 06 15:01:06 prosody[764741]:   Debian/Ubuntu | sudo apt install lua-unbound
> août 06 15:01:06 prosody[764741]:        luarocks | luarocks install luaunbound
> août 06 15:01:06 prosody[764741]:          Source | https://www.zash.se/luaunbound.html
> août 06 15:01:06 prosody[764741]: Old DNS resolver library will be used
> août 06 15:01:06 prosody[764741]: More help can be found on our website, at https://prosody.im/doc/depends
> août 06 15:01:06 prosody[764741]: **************************
> août 06 15:01:06 systemd[1]: prosody.service: Main process exited, code=exited, status=1/FAILURE
> août 06 15:01:06 systemd[1]: prosody.service: Failed with result 'exit-code'.

After running `sudo apt autoremove` Lua 5.4 is removed, Prosody still fails to start.

### Context

- Hardware: ?
- YunoHost version: 11.2.3
- I have access to my server: ?
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: 
- Using, or trying to install package version/branch: master/0.12.3~ynh2
- If upgrading, current package version: 0.12.3~ynh1

### Steps to reproduce

Update to latest version.

### Expected behavior

Prosody works.

### Logs

One of users supplied the following: https://paste.yunohost.org/raw/widikixefa

**Comment by yalh76** [comment]
Can you try to reinstall it ?
I've just tested a install from scratch and prosody service is working well

**Comment by CatsLover71** [comment]
> Can you try to reinstall it ? I've just tested a install from scratch and prosody service is working well

Indeed, uninstall Prosody and reinstall it solved the issue.
