### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/prosody_ynh#9]
### Describe the bug

When upgrading from version `0.11.13~ynh1` to version `0.11.13~ynh2`,  I get this error:
```
Attention : ./upgrade: ligne 101: builddir : variable sans liaison
```

This can be explained by an issue in the [upgrade script](https://github.com/YunoHost-Apps/prosody_ynh/blob/935bdf85822c437459f6d250403b1cbb06943bff/scripts/upgrade):
 - [Line 82](https://github.com/YunoHost-Apps/prosody_ynh/blob/935bdf85822c437459f6d250403b1cbb06943bff/scripts/upgrade#L82), the `builddir` variable only when `"$upgrade_type" == "UPGRADE_APP"`
 - [Line 101](https://github.com/YunoHost-Apps/prosody_ynh/blob/935bdf85822c437459f6d250403b1cbb06943bff/scripts/upgrade#L101), pushd is executed in any type of upgrade, despite `$builddir` being possibly not set.

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: 0.11.13~ynh2
- If upgrading, current package version: 0.11.13~ynh1

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade prosody
    ```

**Comment by yalh76** [comment]
Thanks for the very clear report, I tryed to fix too quickly
